version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_BOT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BOT}
      POSTGRES_DB: db
    ports:
      - "5432:5432"