telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

db:
  driver:
    name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/db
  user: ${POSTGRES_USER_BOT}
  password: ${POSTGRES_PASSWORD_BOT}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: ${POSTGRES_USER_BOT}
    password: ${POSTGRES_PASSWORD_BOT}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update

